### ISSUE TITLE
Crash error: failed to parse ... incomplete N-Quad

### ISSUE THREAD

**Issue by codeisallaround** [cayleygraph/cayley#256]
Is there a flag to ignore parse errors and not crash?

Crash error after about 30 minutes:

    cayley.exe load --config=cayley_freebase.cfg --quads=../../freebase-rdf-latest.gz
    E0523 21:33:31.674522 03968 cayley.go:251] failed to parse "<http://rdf.freebase.com/ns/
    m.01009ly3>\t<http://rdf.freebase.com/ns/wikirecon.wikijoins.wikijoin_proto>\t\t.": 
    incomplete N-Quad

used commands:

    cayley.exe init --config=cayley_freebase.cfg
    cayley.exe load --config=cayley_freebase.cfg --quads=../../freebase-rdf-latest.gz

cayley_freebase.cfg:

    {"database": "leveldb",
    "db_path": "Z:/data/freebase/cayley_leveldb",
    "read_only": false}

I tried to import the last dump of Freebase. I would like to have an offline-copy as they will shut it down in 2-3 months.

LevelDB "LOG" file - last few lines:

    21:33:27.615290 journal@remove removed @10881
    21:33:27.674293 table@build created L1@10888 NÂ·1456 SÂ·96KiB "osW..\xd8\a\t,v23016770":"osY..\xd8\a\t,v24214627"
    21:33:27.881305 table@build created L1@10889 NÂ·29673 SÂ·1MiB "osY..\xd8\a\t,v23175365":"osi..\xd8\a\t,v24014380"
    21:33:28.482340 mem@flush NÂ·41875 SÂ·10MiB
    21:33:28.499341 table@build created L1@10890 NÂ·29783 SÂ·1MiB "osi..\xd8\a\t,v24302505":"os~..\xd8\a\t,v22898712"
    21:33:28.749355 mem@flush created L0@10892 NÂ·41875 SÂ·2MiB "d00..401,v24417551":"z\xff\xe9..N\x1a\xb5,v24458722"
    21:33:28.765356 mem@flush committed FÂ·1 TÂ·266.0153ms
    21:33:28.774356 journal@remove removed @10885
    21:33:28.965367 table@build created L1@10893 NÂ·25106 SÂ·1MiB "os~..\xd8\a\t,v22839624":"os\x91..\xd8\a\t,v22893700"
    21:33:29.157378 table@build created L1@10894 NÂ·22360 SÂ·1MiB "os\x91..\xd8\a\t,v22640645":"os\x9c..\xd8\a\t,v22625945"
    21:33:29.349389 table@build created L1@10895 NÂ·23483 SÂ·1MiB "os\x9c..\xd8\a\t,v22441780":"os\xa7..\xd8\a\t,v22693151"
    21:33:29.549401 table@build created L1@10896 NÂ·22963 SÂ·1MiB "os\xa7..\xd8\a\t,v22810604":"os\xbe..\xd8\a\t,v23235863"
    21:33:29.991426 mem@flush NÂ·41491 SÂ·10MiB
    21:33:30.090432 table@build created L1@10897 NÂ·14953 SÂ·969KiB "os\xbe..\xd8\a\t,v23414361":"os\xcb..\xd8\a\t,v22931677"
    21:33:30.382448 mem@flush created L0@10899 NÂ·41491 SÂ·2MiB "d00..b11,v24459426":"z\xff\xf5..H:\x94,v24499836"
    21:33:30.398449 mem@flush committed FÂ·1 TÂ·308.0177ms
    21:33:30.415450 journal@remove removed @10891
    21:33:30.607461 table@build created L1@10900 NÂ·25234 SÂ·1MiB "os\xcb..\xd8\a\t,v23969643":"os\xdd..\xd8\a\t,v23140191"
    21:33:30.765470 table@build created L1@10901 NÂ·23251 SÂ·1MiB "os\xdd..\xd8\a\t,v23233123":"os\xea..\xd8\a\t,v23283155"
    21:33:30.932480 table@build created L1@10902 NÂ·19963 SÂ·1MiB "os\xea..\xd8\a\t,v23175741":"os\xfe..\xd8\a\t,v23066946"
    21:33:31.057487 table@build created L1@10903 NÂ·16791 SÂ·1MiB "os\xfe..\xd8\a\t,v23080710":"po$..\xd8\a\t,v23283492"
    21:33:31.174494 table@build created L1@10904 NÂ·10360 SÂ·679KiB "po$..\xd8\a\t,v23751203":"po<..\xd8\a\t,v23122286"
    21:33:31.550515 mem@flush NÂ·41434 SÂ·10MiB
    21:33:31.648521 table@build created L1@10905 NÂ·21036 SÂ·1MiB "po\xd4..\xd8\a\t,v23954344":"po\xed..\xd8\a\t,v23100966"

**Comment by kortschak** [comment]
I don't think that allowing automatic inclusion of bad data is a good path to go down. But you can easily clean the stream:

```
// quad-clean parses a stream of RDF quads, splitting the stream
// into good and bad quads. Good quads are printed to stdout and
// bad quads are printed to stderr.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/google/cayley/quad"
	"github.com/google/cayley/quad/cquads"
	"github.com/google/cayley/quad/nquads"
)

var typ = flag.String("type", "cquad", "Specifies quad type to filter.")

func main() {
	flag.Parse()

	var parse func(string) (quad.Quad, error)
	switch *typ {
	case "cquad":
		parse = cquads.Parse
	case "nquad":
		parse = nquads.Parse
	default:
		log.Fatalf("invalid type argument: %q", typ)
	}

	sc := bufio.NewScanner(os.Stdin)
	for sc.Scan() {
		text := sc.Text()
		_, err := parse(text)
		if err == nil {
			fmt.Println(text)
		} else {
			fmt.Fprintln(os.Stderr, text)
		}
	}
	if err := sc.Err(); err != nil {
		log.Fatalf("failed during scanning:", err)
	}
}
```

You can extend this in any way that makes sense to you.

**Comment by codeisallaround** [comment]
Why not ignore such invalid XML parts by default and import only the valid parts as default instead of exit/crash. 

The freebase-rdf-latest.gz is compressed 29GB big, an extra extraction and pre-processing step sounds inefficient. As Freebase is dead, I also hope this doesn't mean the end for this great looking project - there are still DBpedia and Wikidata left.

**Comment by kortschak** [comment]
Happy files are all alike, every unhappy file is unhappy in it's own way.

I've seen different error modes in these files. I don't think it is up to cayley to know all the possible ways a freebase file can be broken. We have a simple and easily validated input strategy. Making cayley do additional parsing reduces that simplicity and makes it harder to validate the correctness. You only need to clean this once, if we did this by default every cayley load from now on would bear the cost of checking for this particular problem, greatly reducing load performance.

**Comment by kortschak** [comment]
To extend on this; at the moment cayley does not support reading data from stdin (there was an attempt at this some time back that hit minor technical difficulties), but if that were added saying `zcat data.gz | quad-clean | cayley --quads=- ...` would actually likely be faster than `cayley --quads=data.gz ...` since zlib's gzip is faster than compress/gzip.

Adding stdin reading would be a worthwhile issue to pick up more generally anyway.

**Comment by codeisallaround** [comment]
I tried to clean the data with your quad-clean code and the following command:

	gzip.exe -cd freebase-rdf-latest.gz | quadclean.exe 1>> freebase.txt 2>> freebase_error.txt

It worked fine, thanks for that! Though 20min in, I got a "Broken pipe" error (due gzip), so to make sure that compressed file isn't broken itself (gzip -t hints that), I am re-downloading the most recent freebase file and try it again.

**Comment by codeisallaround** [comment]
I tried it again with a new freebase dump (no gzip errors). It run fine for several hours but stopped with the following error: 
![cayley](https://cloud.githubusercontent.com/assets/6077471/7901430/5a6635b8-0786-11e5-8a8e-233d9c4721fc.png)

A "insert and ignore" flag would be handy. Cayley should write such info to the stderr and skip that quad but otherwise continue its hour long process. Neither fixing the freebase dump (30GB compressed, 250GB RDF) itself nor restarting on such a minor failure seems reasonable. As Cayley project has been started around the freebase project and is MQL query language, I would have assumed it's regularly tested against the freebase the data dump?

**Comment by kortschak** [comment]
This one?

https://github.com/google/cayley/blob/master/graph/quadwriter.go#L67

$ cayley -help
No command -help

Usage:
  cayley COMMAND [flags]

Commands:
  init      Create an empty database.
  load      Bulk-load a quad file into the database.
  http      Serve an HTTP endpoint on the given host and port.
  repl      Drop into a REPL of the given query language.
  version   Version information.

Flags:
  -alsologtostderr=false: log to standard error as well as files
  -assets="": Explicit path to the HTTP assets.
  -config="": Path to an explicit configuration file.
  -db="memstore": Database Backend.
  -dbpath="/tmp/testdb": Path to the database.
  -format="cquad": Quad format to use for loading ("cquad" or "nquad").
  -host="127.0.0.1": Host to listen on (defaults to all).
  -ignoredup=false: Don't stop loading on duplicated key on add
  -ignoremissing=false: Don't stop loading on missing key on delete
  -load_size=10000: Size of quadsets to load
  -log_backtrace_at=:0: when logging hits line file:N, emit a stack
trace
  -log_dir="": If non-empty, write log files in this directory
  -logstashtype="": enable logstash logging and define the type
  -logstashurl="172.17.42.1:5042": logstash url and port
  -logtostderr=false: log to standard error instead of files
  -port="64210": Port to listen on.
  -prof="": Output profiling file.
  -quads="": Quad file to load before going to REPL.
  -query_lang="gremlin": Use this parser as the query language.
  -read_only=false: Disable writing via HTTP.
  -replication="single": Replication method.
  -stderrthreshold=0: logs at or above this threshold go to stderr
  -timeout=30s: Elapsed time until an individual query times out.
  -v=0: log level for V logs
  -vmodule=: comma-separated list of pattern=N settings for
file-filtered logging

**Comment by codeisallaround** [comment]
Oh sorry, my bad. I read all the documentation files in https://github.com/google/cayley/tree/master/docs including the available configuration settings but I somehow forgot (since last week) about the command lines flags.

**Comment by dennwc** [comment]
Resolved, closing.

**Comment by HarryUlysses** [comment]
> Oh sorry, my bad. I read all the documentation files in https://github.com/google/cayley/tree/master/docs including the available configuration settings but I somehow forgot (since last week) about the command lines flags.

So, In the end, how do you solve your problem?
