### ISSUE TITLE
Using LevelDB with cayley: Error, could not open! file does not exist

### ISSUE THREAD

**Issue by ZhengYang** [cayleygraph/cayley#286]
Configuration file:

```
$ cat cayley.cfg
{
"database": "leveldb",
"db_path": "/cayley_0.4.1_darwin_386/db/",
"read_only": false
}
```

Command: 

```
./cayley repl -ignoredup -dbpath=/wikidata-simple-statements.nt -config=/cayley_0.4.1_darwin_386/cayley.cfg
```

Error:

```
E0726 22:56:50.286284 81645 quadstore.go:118] Error, could not open!  file does not exist
E0726 22:56:50.288093 81645 cayley.go:251] file does not exist
```

**Comment by ds--** [comment]
The config file takes priority over command line, I don't think the -dbpath switch will do anything in your case since the config file has db_path specified.

From the error, I assumed "/cayley_0.4.1_darwin_386/db/" has not been initialized. Was ``./cayley init -config=/cayley_0.4.1_darwin_386/cayley.cfg`` executed prior to running cayley repl?

**Comment by jeffw-wherethebitsroam** [comment]
I had the same issue (for both bolt and leveldb), and running init resolved it. But it would be great if the error message was a bit more helpful! The leveldb message above doesn't give any clue about the issue, bolt just panics with the message:

```
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by carnalim** [comment]
I am having this exact same issue with Level, I don't have a config file created either just using command line parameters: 
./cayley http --db="leveldb" --dbpath=/tmp/leveldb

**Comment by dennwc** [comment]
Since e849da94022cc444921a11b1baabef13ebd7cb10 you need to init database first:
`./cayley init --db="leveldb" --dbpath=/tmp/leveldb`
or
`./cayley http --db="leveldb" --dbpath=/tmp/leveldb --init`

This behavior should be documented better. Ping @robertmeta.

**Comment by robertmeta** [comment]
I think this also needs to be fixed if command line doesn't override config, as I think that is unexpected behavior.

**Comment by healiseu** [comment]
Hi, I am a newcomer and I met this error. It is better I think if you make clear at the beginning of your Quickstart guide that in order to play with any backend you must run these three commands in sequence (initialization, loading, backend), e.g.

1. `./cayley init --db=bolt --dbpath=/tmp/test`
2. `./cayley load --db=bolt --dbpath=/tmp/test --quads=testdata.nq --alsologtostderr`
3. `./cayley repl --db=bolt --dbpath=/tmp/test`

**Comment by jtorvald** [comment]
Just submitted a pull request that hopefully makes this a bit more clear. Although I thought it was already quite clear in the current docs. But maybe it was already changed since this ticket was created. It seems to be old.

**Comment by iddan** [comment]
@dennwc @jtorvald  can this be closed?
