### ISSUE TITLE
Expose Value Comparison Iterator in Gremlin

### ISSUE THREAD

**Issue by barakmich** [cayleygraph/cayley#290]
We already have the iterator, it supports strings as of #262, I'm open for proposals to add it to Gremlin; it shouldn't be too difficult.

**Comment by ds--** [comment]
We don't have anything along Gremlin's normal [Has](http://gremlindocs.com/#filter/has)/[HasNot](http://gremlindocs.com/#filter/hasnot).

**Comment by ds--** [comment]
I have a little followup,

I've recently been experimenting (2fd2be51f07b349b09157aab452e18d9bb08c4ed) with that comparison iterator and extending Has() so that it maintains its existing behavior for backwards compatibility but now allows arrays for predicate/object, example:
* `Who follows dani or greg?` can be more concisely expressed as `g.V().Has("follows", ["dani", "greg"])`.
* `Who follows or likes dani or greg?` can be expressed as `g.V().Has(["follows", "likes"], ["dani", "greg"])`

Additionally I've expended it to also support the [full Gremlin syntax](http://gremlindocs.com/#filter/has) for `Has()` when 3 arguments are provided `Has(<predicate>, <operator>, <value[s]>)` For example:
* `Who is over 25?`, assuming our test data had a few age predicates, would be expressed as `g.V().Has("age", T.gt, 25)`
* `Who is 18 or 21?` can be expressed as `g.V().Has("age", T.in, [18, 21])`

With a few additions to allow a few more text related comparisons: (for example case insensitivity here)
* `Who is from the US or UK?` would be `g.V().Has("country", T.Text.iin, ["UK", "USA"])`

I am looking for some feedback on everything (syntax, code itself). Looking for some approval on this direction.
