### ISSUE TITLE
How to fetch outgoing edge/vertex pairs for a given vertex?

### ISSUE THREAD

**Issue by batwicket** [cayleygraph/cayley#387]
I would like to efficiently gather a list of {edge label : vertex label} pairs for a specific vertex. Gremlin/MQL seem good for finding the vertex but my impression is that they aren't suited to gathering the pairs.

Currently I'm looking into fetching the id via gremlin then using golang to locate the corresponding struct instance and iterate over the pairs. Any insights appreciated!

Also posted to http://stackoverflow.com/questions/36406007/what-is-an-efficient-method-to-gather-all-vertex-properties-with-cayley-graph-da .

**Comment by dennwc** [comment]
@batwicket Try this query:
```js
g.V("vertex_id").Out(g.V(),"edge").Save("vertex")
```
Returned objects can be merged into a single list later.

If you are using Cayley as a library from Golang, there is a better way of achieving the same result.
You can check how path lib does Out and Save and write your own function which does the same query shape, but instead of tagging nodes it should iterate over links, do QuadDirection on QuadStore with the tokens from iterator for predicate and object directions and then asking QS for a name of the these node.

**Comment by adkatrit** [comment]
It would be helpful to show an example implementation of using Cayley as a library from Golang in Cayley's documentation.  It's not obvious how one would go about this without digging into some source.

**Comment by oren** [comment]
:+1: 

The only example I found is from the wiki - https://github.com/google/cayley/wiki/Cayley-Go-API-(as-a-Library-in-your-own-projects).

**Comment by rusenask** [comment]
`*path.Path` has methods like `.And(*Path)` where you can combine multiple paths :)
<img width="612" alt="screen shot 2016-04-04 at 21 00 34" src="https://cloud.githubusercontent.com/assets/9080105/14261417/5b84fbc6-faa8-11e5-930a-697e81b5b273.png">

**Comment by adkatrit** [comment]
@oren i didn't look at the wiki.   doh!

**Comment by dennwc** [comment]
The path lib is one-to-one replacement for Gremlin, but it is designed to be nodes-centric for some reason (except InPredicates/OutPredicates that were added later). So, it's more efficient to use iterators directly to build the necessary query shape and get both predicate and object in one step instead of letting the optimizer to merge the trees generated by path lib (I believe it will not do that for this particular query).

**Comment by batwicket** [comment]
thanks for the info dennwc - appreciated. I looked at Barak's GopherCon video, Scott Meyer's "A Brief Tour of GraphD", and a bit of Freebase so maybe i'm getting to the point where i can start to understand some of the Cayley data structures. 

I see that issue #388 mentions Loop() - that seems like it might be ok, too.

**Comment by robertmeta** [comment]
This is actually going to go in the Cayley Cookbook -- https://discourse.cayley.io/t/building-a-cayley-cookbook/172/10 -- let me know if there is a reason I should keep this independently open.
