### ISSUE TITLE
An already existing quad can't be replaced/updated from HTTP API since 0.6.1

### ISSUE THREAD

**Issue by MichelBoucey** [cayleygraph/cayley#583]
In previous versions, `/api/v1/write` used to accept to write a quad _and_ replace/update an already existing quad, but this is no more true. It returns since Cayley 0.6.1 an error "quad exists". But no `/api/v1/update` yet?

**Comment by dennwc** [comment]
This is a correct behavior introduced because of https://github.com/cayleygraph/cayley/commit/5fb76a869c3bd12d8bc74c1140931651562aa792#diff-da37c97d3f13278e12c4b9ac2525e430R76. Previous Write API v1 ignored errors completely. Now they are returned properly in responses.

The real cause of an error is that Cayley was run without `-ignoredup` flag. Passing it will solve an issue.

Starting from v0.6.2 / v0.7 we will ignore duplicates by default.

**Comment by MichelBoucey** [comment]
1°/ So it is possible to have duplicate quads!? 2°/ How to replace/update a quad though?

**Comment by dennwc** [comment]
> So it is possible to have duplicate quads!?
No, but you can choose if transaction will fail because of this attempt or not.

> How to replace/update a quad though?
Replace is usually a transaction with removal of old quad and addition of a new one.

**Comment by MichelBoucey** [comment]
Thank you for details.

FYI I've implemented Cayley HTTP API v1 in Haskell ([cayley-client](https://hackage.haskell.org/package/cayley-client)). So I will have questions in futur to implement it with Cayley > 0.6.0.
