### ISSUE TITLE
Inserting struct via `schema.WriteAsQuads` where a field is empty string causes weird behavior with `schema.LoadTo`

### ISSUE THREAD

**Issue by oren** [cayleygraph/cayley#602]
**Description**
I insert an admin using `schema.WriteAsQuads` while one of the fields is empty string.
And `schema.LoadTo(nil, store, &admins)` shows nothing. Is that expected?

**Steps to reproduce the issue:**
1. Run `go run main.go` on [this](https://github.com/oren/test-cayley/blob/b09ab314439dbe8a35202edf31568fa7064d9e7c/schema/bug/main.go) file.

**Received results:**
`schema.LoadTo(nil, store, &admins)` shows nothing despite the fact that 3 out of 4 quads of an admin exist:
```
<cf86> -- <rdf:type> -> <Admin>
<cf86> -- <email> -> "foo@gmail.com"
<cf86> -- <hashed_password> -> "phyhyhyh"
```

**Expected results:**
I would think that `LoadTo` will return an admin.

**Output of `cayley version` or commit hash:**

```
Cayley version: 0.7.0-alpha
```

**Environment details:**

Backend database: `(database and version)`

**Comment by dennwc** [comment]
This is not a bug, but this should probably return an error.

Here is what happens:
1) Admin structure is inserted, but Name quad is omited, since it's empty.
2) When loading, Name is interpreted as required field and since there is no such quad, no Admins will be returned.

Clearly, the Name should be an optional field in this case. However, I can prevent such mistakes by returning an error if one of required fields is empty on write. The problem is, it will not rollback already written values automatically, since it does not control the writer.

**Comment by oren** [comment]
Thanks! is there a way to have optional field?

**Comment by dennwc** [comment]
Sure, try `quad:"name,optional"`

**Comment by oren** [comment]
thanks. is this go feature or something specific to schema lib?

**Comment by dennwc** [comment]
Specific to the lib. The closest analog from stdlib is `,omitempty` in json.

**Comment by oren** [comment]
gotcha. thanks
