### ISSUE TITLE
Feature: Get a random vertex

### ISSUE THREAD

**Issue by jsmorph** [cayleygraph/cayley#66]
Feature request: Get a random vertex (in constant time).

Even better: given a range, get a random vertex in that range in constant time.

Why?  Because sometimes a datastore (e.g., hash tables) can easily get random entries when the application cannot.  Getting a random thing can be very help for sampling, tests, and statistical analysis in general.

Being able to get a random in/out edge for a given vertex could also be handy in some cases.

I haven't looked that the hashing for the different back ends, but hopefully the non-ranged-based version turns out to be easy to implement.  I'll take a look soon, I hope.

**Comment by Quentin-M** [comment]
:+1:

Being able to get random results from a path / iterator would be nice. In my case, multiple workers get elements one by one from the database, lock the resource and do things with them. Because they are selected in the same order on each worker, the workers are likely to get the same one, even if there are a lot of them and try to lock it at the same time.

A temporary application-side workaround is to select few and return a random.

**Comment by robertmeta** [comment]
This is a really great idea -- for the moment until we get a little more of a concrete implementation idea, moving to it the feature request section of the forum: https://discourse.cayley.io/t/feature-get-a-random-vertex/197
