### ISSUE TITLE
Add Health Status endpoint

### ISSUE THREAD

**Issue by iddan** [cayleygraph/cayley#804]
**Description**
When the server starts there is a delay until it listens to incoming requests.

**Steps to reproduce the issue:**
1. Start a server
2. Immediately try to connect 
3. Connection failure

**Expected results:**

Server to receive the request and response when ready.

**Comment by dennwc** [comment]
Sorry, I don't understand what is the expected behavior. For example, if Cayley starts with `-i` it will first load the data and after it's done it will open a port for serving HTTP connections. This operation may take hours, and while batch import is running we cannot serve any queries.

We can add a [liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request) if it helps. After `/healthz` endpoint returns status `200`, Cayley should be ready to serve requests. Will it solve the issue?

**Comment by iddan** [comment]
Yeah

**Comment by iddan** [comment]
Once this is done we can add a healthcheck for the dockerfile
