### ISSUE TITLE
Seeking for a new maintainer

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/cayley#963]
The project is in a "zombie state" for a while now. It would be awesome if someone could take over the development.

**Comment by askender** [comment]
I'm using Cayley since several years ago. So sorry I don't pull-request anything until now.

I'm willing to take over the development because I'm full-time independent developer now and have time for it.     I'm also start developing an open-source and open-data dweb search engine:  https://dweb-search.on.fleek.co/

I'm an NLP researcher for years.  These are several papers of mine: https://scholar.google.com/citations?hl=zh-CN&user=tzIrta0AAAAJ  

I'm also thinking about building a open-source knowledge-graph project and hope Cayley can be better.

Hope I'm qualified for being a cayley maintainer.

**Comment by eraserhd** [comment]
I shouldn't be in charge, but I'm willing to help.  I've maintained a few OSS projects.

I'm planning on adding some features for personal use (quad file formats, aggregating back ends, maybe SPARQL or improve the Lisp query), starting next year probably.

**Comment by schauhan16** [comment]
I have never maintained any project but would like to contribute.

I am a software engineer with experience in various domains.

**Comment by barakmich** [comment]
I'm still here too; granted we still need someone to take over primary development/maintenance, but I'm here if interested parties want to chat :)

**Comment by paralin** [comment]
I'm using cayley in some projects, and have contributed a couple PRs in the past. Will continue to submit any fixes from my forks.

**Comment by eraserhd** [comment]
Alright, I formally request organization membership, write access and admin privileges.  I’m some rando, but if I seem trustworthy, my plan is to:

* Move the site to GitHub pages
* Review and merge obvious small PRs (bug fixes, documentation changes, etc.)
* Request review from others who are relevant to the topic or invested in the functionality on big PRs.

In terms of direction of the project, I hope to mostly be just a steward.  I have my own agenda for features, but I’ll own that.

My own agenda is about federation: making lighter weight and composable backends, like a single-file read-only back end, and an aggregating backend, perhaps a rule engine backend, and an external program backend, so that graph queries can be made across multiple sources.  And perhaps SPARQL.

About me:

Moved to Go a few months ago after being a Clojurist for seven years, extensively worked with Datomic (a triplestore) and Clara Rules (a rete-style inference engine).  A lot of the plumbing in the Clojure system I was the lead on was about translating different meta-schema formats - e.g. JSON Schema to Datomic schema, and to GraphQL schema, etc., to create basically a knowledge system that was nearly entirely declaratively driven.  (The system is internal to my org.)

Currently maintain: `parinfer-rust` a popular port of a Clojure editor plugin, and `rep` a unix-philosophy-style command-line program that serves as a REPL integration for editors that like unix-philosophy-style things.  In the past, I’ve maintained a lot of things, the first one was the Linux 5250 emulator.

**Comment by paralin** [comment]
I'm also happy to contribute / review PRs, since I'm now depending on Cayley for graph storage.

**Comment by dennwc** [comment]
Formally accepting request by @eraserhd. You indeed have relevant experience to push it forward I think :)

A second request was made by @askender, but I don't really see relevant projects in your profile, unfortunately. I'd seek for C/Go background, to be specific.

**Comment by eraserhd** [comment]
@dennwc Thanks!

I'm going to block off a couple hours twice a week to start.

**Comment by eraserhd** [comment]
@denwc I'd like to move the site to GitHub pages to bring it back up, but I can't create repos in `cayleygraph`.  Could you:

1. Rename the `website` repo to `cayleygraph.github.io`
2. Give me admin on it.
3. Make cayley.io a CNAME for `cayleygraph.github.io`.

I can sort out the rest.

Thanks.

**Comment by dennwc** [comment]
@eraserhd steps 1 and 2 done, thank you for taking care of this! :bowing_man: 

I cannot do step 3 because I do not control the domain. I think @barakmich might still have access to it.

**Comment by paralin** [comment]
@dennwc I'm working on [a fork](https://github.com/aperturerobotics/cayley) and am happy to submit any bugfixes (not major overhauls like the ascii-key changes) upstream & maintain if you'd like.
